//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAATService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_WODAMAGE
    {
        public int WO_ID { get; set; }
        public string EQPNO { get; set; }
        public string MODE { get; set; }
        public string SHOP_CD { get; set; }
        public string SHOP_LOC_CD { get; set; }
        public string CURR_MOVE { get; set; }
        public string CURR_LOC_CD { get; set; }
        public string MERC_DAMAGE { get; set; }
        public string RKEM_DAMAGE { get; set; }
        public int RKEM_STATUS { get; set; }
        public System.DateTime CRTS { get; set; }
    }
}
