//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageAATService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_AUTHGROUP
    {
        public SEC_AUTHGROUP()
        {
            this.SEC_AUTHGROUP_USER = new HashSet<SEC_AUTHGROUP_USER>();
        }
    
        public int AUTHGROUP_ID { get; set; }
        public string AUTHGROUP_NAME { get; set; }
        public int PARENT_AUTHGROUP_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string COLUMN_DESC { get; set; }
        public string READONLY_SW { get; set; }
    
        public virtual SEC_AUTHGROUP SEC_AUTHGROUP1 { get; set; }
        public virtual SEC_AUTHGROUP SEC_AUTHGROUP2 { get; set; }
        public virtual ICollection<SEC_AUTHGROUP_USER> SEC_AUTHGROUP_USER { get; set; }
    }
}
