//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKRP_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EQMODE
    {
        public int EQMODE_ID { get; set; }
        public string EQSTYPE { get; set; }
        public string EQSIZE { get; set; }
        public string MODE { get; set; }
        public string COTYPE { get; set; }
        public string CHUSER { get; set; }
        public string ALUMINIUM_SW { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_MODE MESC1TS_MODE { get; set; }
    }
}
