//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKRP_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_MODEL
    {
        public string MODEL_NO { get; set; }
        public string INDICATOR_CD { get; set; }
        public string MANUFCTR { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_MANUFACTUR MESC1TS_MANUFACTUR { get; set; }
    }
}
