//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKRP_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EVENT_LOG
    {
        public int EVENT_ID { get; set; }
        public string EVENT_NAME { get; set; }
        public string UNIQUE_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string EVENT_DESC { get; set; }
        public string CHUSER { get; set; }
        public Nullable<System.DateTime> CHTS { get; set; }
    }
}
