//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merc_INLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_SHOP_CONT
    {
        public int SHOP_CONT_ID { get; set; }
        public string SHOP_CD { get; set; }
        public string MODE { get; set; }
        public string REPAIR_CD { get; set; }
        public Nullable<decimal> CONTRACT_AMOUNT { get; set; }
        public System.DateTime EFF_DTE { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime EXP_DTE { get; set; }
        public System.DateTime CHTS { get; set; }
        public string MANUAL_CD { get; set; }
    
        public virtual MESC1TS_SHOP MESC1TS_SHOP { get; set; }
    }
}
