//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merc_INLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EDI_TRANSMISSION
    {
        public int EDI_ID { get; set; }
        public Nullable<System.DateTime> CRTS { get; set; }
        public Nullable<int> WO_QTY { get; set; }
        public Nullable<int> WO_PASS_QTY { get; set; }
        public Nullable<int> WO_FAIL_QTY { get; set; }
    }
}
