//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merc_INLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1VS_CUST_SHOP
    {
        public string CUSTOMER_CD { get; set; }
        public string SHOP_CD { get; set; }
    }
}
