//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merc_INLC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_WEBSITE
    {
        public SEC_WEBSITE()
        {
            this.SEC_WEBPAGE = new HashSet<SEC_WEBPAGE>();
            this.SEC_AUTHGROUP = new HashSet<SEC_AUTHGROUP>();
        }
    
        public int WEBSITE_ID { get; set; }
        public string WEBSITE_NAME { get; set; }
    
        public virtual ICollection<SEC_WEBPAGE> SEC_WEBPAGE { get; set; }
        public virtual ICollection<SEC_AUTHGROUP> SEC_AUTHGROUP { get; set; }
    }
}
