//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_PAYAGENT
    {
        public MESC1TS_PAYAGENT()
        {
            this.MESC1TS_CUST_SHOP_MODE = new HashSet<MESC1TS_CUST_SHOP_MODE>();
            this.MESC1TS_PAYAGENT_VENDOR = new HashSet<MESC1TS_PAYAGENT_VENDOR>();
        }
    
        public string PAYAGENT_CD { get; set; }
        public string CORP_PAYAGENT_CD { get; set; }
        public string RRIS_FORMAT { get; set; }
        public string PROFIT_CENTER { get; set; }
        public string SUB_PROFIT_CENTER { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_CUST_SHOP_MODE> MESC1TS_CUST_SHOP_MODE { get; set; }
        public virtual ICollection<MESC1TS_PAYAGENT_VENDOR> MESC1TS_PAYAGENT_VENDOR { get; set; }
    }
}
