//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EDI_LINEITEM
    {
        public int EDI_ID { get; set; }
        public Nullable<int> LINE_NO { get; set; }
        public string LINE_DETAIL { get; set; }
    }
}
