//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_WOAUDIT
    {
        public int WO_ID { get; set; }
        public string AUDIT_TEXT { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    }
}
