//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_CUST_SHOP_MODE
    {
        public string CSM_CD { get; set; }
        public string MODE { get; set; }
        public string RRIS_FORMAT { get; set; }
        public string SHOP_CD { get; set; }
        public string PROFIT_CENTER { get; set; }
        public string PAYAGENT_CD { get; set; }
        public string SUB_PROFIT_CENTER { get; set; }
        public string ACCOUNT_CD { get; set; }
        public string CUSTOMER_CD { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
        public string CORP_PAYAGENT_CD { get; set; }
    
        public virtual MESC1TS_CUSTOMER MESC1TS_CUSTOMER { get; set; }
        public virtual MESC1TS_PAYAGENT MESC1TS_PAYAGENT { get; set; }
        public virtual MESC1TS_SHOP MESC1TS_SHOP { get; set; }
        public virtual MESC1TS_MODE MESC1TS_MODE { get; set; }
    }
}
