//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test2Table
    {
        public int USER_ID { get; set; }
        public string LOGIN { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string COMPANY { get; set; }
        public string LOC_CD { get; set; }
        public string ACTIVE_STATUS { get; set; }
        public Nullable<decimal> APPROVAL_AMOUNT { get; set; }
    }
}
