//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test1Table
    {
        public int ACCESS_ID { get; set; }
        public int AUTHGROUP_ID { get; set; }
        public int USER_ID { get; set; }
        public string COLUMN_VALUE { get; set; }
    }
}
