//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercFACTUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1VS_SHOP_LOCATION
    {
        public string SHOP_CD { get; set; }
        public string VENDOR_CD { get; set; }
        public string SHOP_DESC { get; set; }
        public string CUCDN { get; set; }
        public string PREPTIME_SW { get; set; }
        public string LOC_CD { get; set; }
        public string REGION_CD { get; set; }
        public string COUNTRY_CD { get; set; }
        public string AREA_CD { get; set; }
        public string SHOP_ACTIVE_SW { get; set; }
        public Nullable<double> PCT_MATERIAL_FACTOR { get; set; }
        public Nullable<double> IMPORT_TAX { get; set; }
        public Nullable<double> SALES_TAX_PART_CONT { get; set; }
        public Nullable<double> SALES_TAX_PART_GEN { get; set; }
        public Nullable<double> SALES_TAX_LABOR_CON { get; set; }
        public Nullable<double> SALES_TAX_LABOR_GEN { get; set; }
        public string SHOP_TYPE_CD { get; set; }
        public string OVERTIME_SUSP_SW { get; set; }
        public string AUTO_COMPLETE_SW { get; set; }
        public string BYPASS_LEASE_RULES { get; set; }
        public string DECENTRALIZED { get; set; }
    }
}
