//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercFACTUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_STATUS_CODE
    {
        public MESC1TS_STATUS_CODE()
        {
            this.MESC1TS_WO = new HashSet<MESC1TS_WO>();
        }
    
        public short STATUS_CODE { get; set; }
        public string STATUS_DSC { get; set; }
    
        public virtual ICollection<MESC1TS_WO> MESC1TS_WO { get; set; }
    }
}
