//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercFACTUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_NONSCODE
    {
        public string MODE { get; set; }
        public string NONS_CD { get; set; }
        public string NONS_DESC { get; set; }
        public string NONS_ACTIVE_SW { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_MODE MESC1TS_MODE { get; set; }
    }
}
