//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercFACTUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EQTYPE
    {
        public MESC1TS_EQTYPE()
        {
            this.MESC1TS_COUNTRY_LABOR = new HashSet<MESC1TS_COUNTRY_LABOR>();
            this.MESC1TS_LABOR_RATE = new HashSet<MESC1TS_LABOR_RATE>();
            this.MESC1TS_WO = new HashSet<MESC1TS_WO>();
        }
    
        public string EQTYPE { get; set; }
        public string EQTYPE_DESC { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_COUNTRY_LABOR> MESC1TS_COUNTRY_LABOR { get; set; }
        public virtual ICollection<MESC1TS_LABOR_RATE> MESC1TS_LABOR_RATE { get; set; }
        public virtual ICollection<MESC1TS_WO> MESC1TS_WO { get; set; }
    }
}
