//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercFACTUpload
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_MASTER_PART
    {
        public MESC1TS_MASTER_PART()
        {
            this.MESC1TS_RPRCODE_PART = new HashSet<MESC1TS_RPRCODE_PART>();
            this.MESC1TS_WOPART = new HashSet<MESC1TS_WOPART>();
        }
    
        public string PARTS_GROUP_CD { get; set; }
        public string PART_CD { get; set; }
        public string PART_DESC { get; set; }
        public Nullable<decimal> PART_PRICE { get; set; }
        public string CHUSER { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public string PART_DESIGNATION_1 { get; set; }
        public System.DateTime CHTS { get; set; }
        public string PART_DESIGNATION_2 { get; set; }
        public string PART_DESIGNATION_3 { get; set; }
        public string PART_ACTIVE_SW { get; set; }
        public Nullable<decimal> CORE_VALUE { get; set; }
        public string DEDUCT_CORE { get; set; }
        public string REMARKS { get; set; }
        public string MANUFCTR { get; set; }
        public string CORE_PART_SW { get; set; }
        public string MSL_PART_SW { get; set; }
    
        public virtual MESC1TS_MANUFACTUR MESC1TS_MANUFACTUR { get; set; }
        public virtual MESC1TS_PARTS_GROUP MESC1TS_PARTS_GROUP { get; set; }
        public virtual ICollection<MESC1TS_RPRCODE_PART> MESC1TS_RPRCODE_PART { get; set; }
        public virtual ICollection<MESC1TS_WOPART> MESC1TS_WOPART { get; set; }
    }
}
