//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusClient.ManageHSUDDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstLifeCycle_ApprovalCanceled", Namespace="http://schemas.datacontract.org/2004/07/ManageHSUDDataService")]
    [System.SerializableAttribute()]
    public partial class EstLifeCycle_ApprovalCanceled : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Approved_ByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base_Currency_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base_Currency_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cancelled_ByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cancelled_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquimentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Estimate_Grand_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Estimate_Grand_Total_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Estimate_Original_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estimate_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Estimate_Transmission_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Facility_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Facility_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Onwer_Approval_Number_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Owner_Approval_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Handling_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Labor_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Material_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Tax_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_handling_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_labor_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_material_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_tax_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Revision_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Summary_Size_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyrequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_handling_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_material_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_tax_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_total_labor_originalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Approved_By {
            get {
                return this.Approved_ByField;
            }
            set {
                if ((object.ReferenceEquals(this.Approved_ByField, value) != true)) {
                    this.Approved_ByField = value;
                    this.RaisePropertyChanged("Approved_By");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base_Currency_Approved {
            get {
                return this.Base_Currency_ApprovedField;
            }
            set {
                if ((object.ReferenceEquals(this.Base_Currency_ApprovedField, value) != true)) {
                    this.Base_Currency_ApprovedField = value;
                    this.RaisePropertyChanged("Base_Currency_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base_Currency_Original {
            get {
                return this.Base_Currency_OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.Base_Currency_OriginalField, value) != true)) {
                    this.Base_Currency_OriginalField = value;
                    this.RaisePropertyChanged("Base_Currency_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cancelled_By {
            get {
                return this.Cancelled_ByField;
            }
            set {
                if ((object.ReferenceEquals(this.Cancelled_ByField, value) != true)) {
                    this.Cancelled_ByField = value;
                    this.RaisePropertyChanged("Cancelled_By");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cancelled_Date {
            get {
                return this.Cancelled_DateField;
            }
            set {
                if ((object.ReferenceEquals(this.Cancelled_DateField, value) != true)) {
                    this.Cancelled_DateField = value;
                    this.RaisePropertyChanged("Cancelled_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquimentID {
            get {
                return this.EquimentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EquimentIDField, value) != true)) {
                    this.EquimentIDField = value;
                    this.RaisePropertyChanged("EquimentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentType {
            get {
                return this.EquipmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentTypeField, value) != true)) {
                    this.EquipmentTypeField = value;
                    this.RaisePropertyChanged("EquipmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstimateNumber {
            get {
                return this.EstimateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimateNumberField, value) != true)) {
                    this.EstimateNumberField = value;
                    this.RaisePropertyChanged("EstimateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Estimate_Grand_Total_Approved {
            get {
                return this.Estimate_Grand_Total_ApprovedField;
            }
            set {
                if ((this.Estimate_Grand_Total_ApprovedField.Equals(value) != true)) {
                    this.Estimate_Grand_Total_ApprovedField = value;
                    this.RaisePropertyChanged("Estimate_Grand_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Estimate_Grand_Total_Original {
            get {
                return this.Estimate_Grand_Total_OriginalField;
            }
            set {
                if ((this.Estimate_Grand_Total_OriginalField.Equals(value) != true)) {
                    this.Estimate_Grand_Total_OriginalField = value;
                    this.RaisePropertyChanged("Estimate_Grand_Total_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Estimate_Original_Date {
            get {
                return this.Estimate_Original_DateField;
            }
            set {
                if ((this.Estimate_Original_DateField.Equals(value) != true)) {
                    this.Estimate_Original_DateField = value;
                    this.RaisePropertyChanged("Estimate_Original_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estimate_Status {
            get {
                return this.Estimate_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Estimate_StatusField, value) != true)) {
                    this.Estimate_StatusField = value;
                    this.RaisePropertyChanged("Estimate_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Estimate_Transmission_date {
            get {
                return this.Estimate_Transmission_dateField;
            }
            set {
                if ((this.Estimate_Transmission_dateField.Equals(value) != true)) {
                    this.Estimate_Transmission_dateField = value;
                    this.RaisePropertyChanged("Estimate_Transmission_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facility_Code {
            get {
                return this.Facility_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Facility_CodeField, value) != true)) {
                    this.Facility_CodeField = value;
                    this.RaisePropertyChanged("Facility_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facility_Name {
            get {
                return this.Facility_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Facility_NameField, value) != true)) {
                    this.Facility_NameField = value;
                    this.RaisePropertyChanged("Facility_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Onwer_Approval_Number_Original {
            get {
                return this.Onwer_Approval_Number_OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.Onwer_Approval_Number_OriginalField, value) != true)) {
                    this.Onwer_Approval_Number_OriginalField = value;
                    this.RaisePropertyChanged("Onwer_Approval_Number_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Owner_Approval_Date {
            get {
                return this.Owner_Approval_DateField;
            }
            set {
                if ((this.Owner_Approval_DateField.Equals(value) != true)) {
                    this.Owner_Approval_DateField = value;
                    this.RaisePropertyChanged("Owner_Approval_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Handling_Approved {
            get {
                return this.Owner_Handling_ApprovedField;
            }
            set {
                if ((this.Owner_Handling_ApprovedField.Equals(value) != true)) {
                    this.Owner_Handling_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Handling_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Labor_Approved {
            get {
                return this.Owner_Labor_ApprovedField;
            }
            set {
                if ((this.Owner_Labor_ApprovedField.Equals(value) != true)) {
                    this.Owner_Labor_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Labor_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Material_Approved {
            get {
                return this.Owner_Material_ApprovedField;
            }
            set {
                if ((this.Owner_Material_ApprovedField.Equals(value) != true)) {
                    this.Owner_Material_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Material_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Tax_Approved {
            get {
                return this.Owner_Tax_ApprovedField;
            }
            set {
                if ((this.Owner_Tax_ApprovedField.Equals(value) != true)) {
                    this.Owner_Tax_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Tax_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Total_Approved {
            get {
                return this.Owner_Total_ApprovedField;
            }
            set {
                if ((this.Owner_Total_ApprovedField.Equals(value) != true)) {
                    this.Owner_Total_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_handling_original {
            get {
                return this.Owner_total_handling_originalField;
            }
            set {
                if ((this.Owner_total_handling_originalField.Equals(value) != true)) {
                    this.Owner_total_handling_originalField = value;
                    this.RaisePropertyChanged("Owner_total_handling_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_labor_original {
            get {
                return this.Owner_total_labor_originalField;
            }
            set {
                if ((this.Owner_total_labor_originalField.Equals(value) != true)) {
                    this.Owner_total_labor_originalField = value;
                    this.RaisePropertyChanged("Owner_total_labor_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_material_original {
            get {
                return this.Owner_total_material_originalField;
            }
            set {
                if ((this.Owner_total_material_originalField.Equals(value) != true)) {
                    this.Owner_total_material_originalField = value;
                    this.RaisePropertyChanged("Owner_total_material_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_original {
            get {
                return this.Owner_total_originalField;
            }
            set {
                if ((this.Owner_total_originalField.Equals(value) != true)) {
                    this.Owner_total_originalField = value;
                    this.RaisePropertyChanged("Owner_total_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_tax_original {
            get {
                return this.Owner_total_tax_originalField;
            }
            set {
                if ((this.Owner_total_tax_originalField.Equals(value) != true)) {
                    this.Owner_total_tax_originalField = value;
                    this.RaisePropertyChanged("Owner_total_tax_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Revision_Number {
            get {
                return this.Revision_NumberField;
            }
            set {
                if ((this.Revision_NumberField.Equals(value) != true)) {
                    this.Revision_NumberField = value;
                    this.RaisePropertyChanged("Revision_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary_Size_Type {
            get {
                return this.Summary_Size_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Summary_Size_TypeField, value) != true)) {
                    this.Summary_Size_TypeField = value;
                    this.RaisePropertyChanged("Summary_Size_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surveyrequested {
            get {
                return this.SurveyrequestedField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyrequestedField, value) != true)) {
                    this.SurveyrequestedField = value;
                    this.RaisePropertyChanged("Surveyrequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_Approved {
            get {
                return this.User_Total_ApprovedField;
            }
            set {
                if ((this.User_Total_ApprovedField.Equals(value) != true)) {
                    this.User_Total_ApprovedField = value;
                    this.RaisePropertyChanged("User_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_Original {
            get {
                return this.User_Total_OriginalField;
            }
            set {
                if ((this.User_Total_OriginalField.Equals(value) != true)) {
                    this.User_Total_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_handling_Original {
            get {
                return this.User_Total_handling_OriginalField;
            }
            set {
                if ((this.User_Total_handling_OriginalField.Equals(value) != true)) {
                    this.User_Total_handling_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_handling_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_material_Original {
            get {
                return this.User_Total_material_OriginalField;
            }
            set {
                if ((this.User_Total_material_OriginalField.Equals(value) != true)) {
                    this.User_Total_material_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_material_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_tax_Original {
            get {
                return this.User_Total_tax_OriginalField;
            }
            set {
                if ((this.User_Total_tax_OriginalField.Equals(value) != true)) {
                    this.User_Total_tax_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_tax_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_total_labor_original {
            get {
                return this.User_total_labor_originalField;
            }
            set {
                if ((this.User_total_labor_originalField.Equals(value) != true)) {
                    this.User_total_labor_originalField = value;
                    this.RaisePropertyChanged("User_total_labor_original");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstLifeCycleAnalysi", Namespace="http://schemas.datacontract.org/2004/07/ManageHSUDDataService")]
    [System.SerializableAttribute()]
    public partial class EstLifeCycleAnalysi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Approved_ByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base_Currency_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base_Currency_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cancelled_ByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Cancelled_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquimentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Estimate_Grand_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Estimate_Grand_Total_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Estimate_Original_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Estimate_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Estimate_Transmission_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Facility_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Facility_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Onwer_Approval_Number_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Owner_Approval_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Handling_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Labor_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Material_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Tax_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_handling_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_labor_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_material_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Owner_total_tax_originalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Repair_Complete_ReportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Repair_Completed_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Revision_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Summary_Size_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyrequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_ApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_handling_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_material_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_Total_tax_OriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> User_total_labor_originalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Approved_By {
            get {
                return this.Approved_ByField;
            }
            set {
                if ((object.ReferenceEquals(this.Approved_ByField, value) != true)) {
                    this.Approved_ByField = value;
                    this.RaisePropertyChanged("Approved_By");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base_Currency_Approved {
            get {
                return this.Base_Currency_ApprovedField;
            }
            set {
                if ((object.ReferenceEquals(this.Base_Currency_ApprovedField, value) != true)) {
                    this.Base_Currency_ApprovedField = value;
                    this.RaisePropertyChanged("Base_Currency_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base_Currency_Original {
            get {
                return this.Base_Currency_OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.Base_Currency_OriginalField, value) != true)) {
                    this.Base_Currency_OriginalField = value;
                    this.RaisePropertyChanged("Base_Currency_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cancelled_By {
            get {
                return this.Cancelled_ByField;
            }
            set {
                if ((object.ReferenceEquals(this.Cancelled_ByField, value) != true)) {
                    this.Cancelled_ByField = value;
                    this.RaisePropertyChanged("Cancelled_By");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Cancelled_Date {
            get {
                return this.Cancelled_DateField;
            }
            set {
                if ((this.Cancelled_DateField.Equals(value) != true)) {
                    this.Cancelled_DateField = value;
                    this.RaisePropertyChanged("Cancelled_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquimentID {
            get {
                return this.EquimentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EquimentIDField, value) != true)) {
                    this.EquimentIDField = value;
                    this.RaisePropertyChanged("EquimentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentType {
            get {
                return this.EquipmentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentTypeField, value) != true)) {
                    this.EquipmentTypeField = value;
                    this.RaisePropertyChanged("EquipmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstimateNumber {
            get {
                return this.EstimateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimateNumberField, value) != true)) {
                    this.EstimateNumberField = value;
                    this.RaisePropertyChanged("EstimateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Estimate_Grand_Total_Approved {
            get {
                return this.Estimate_Grand_Total_ApprovedField;
            }
            set {
                if ((this.Estimate_Grand_Total_ApprovedField.Equals(value) != true)) {
                    this.Estimate_Grand_Total_ApprovedField = value;
                    this.RaisePropertyChanged("Estimate_Grand_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Estimate_Grand_Total_Original {
            get {
                return this.Estimate_Grand_Total_OriginalField;
            }
            set {
                if ((this.Estimate_Grand_Total_OriginalField.Equals(value) != true)) {
                    this.Estimate_Grand_Total_OriginalField = value;
                    this.RaisePropertyChanged("Estimate_Grand_Total_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Estimate_Original_Date {
            get {
                return this.Estimate_Original_DateField;
            }
            set {
                if ((this.Estimate_Original_DateField.Equals(value) != true)) {
                    this.Estimate_Original_DateField = value;
                    this.RaisePropertyChanged("Estimate_Original_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estimate_Status {
            get {
                return this.Estimate_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Estimate_StatusField, value) != true)) {
                    this.Estimate_StatusField = value;
                    this.RaisePropertyChanged("Estimate_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Estimate_Transmission_date {
            get {
                return this.Estimate_Transmission_dateField;
            }
            set {
                if ((this.Estimate_Transmission_dateField.Equals(value) != true)) {
                    this.Estimate_Transmission_dateField = value;
                    this.RaisePropertyChanged("Estimate_Transmission_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facility_Code {
            get {
                return this.Facility_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Facility_CodeField, value) != true)) {
                    this.Facility_CodeField = value;
                    this.RaisePropertyChanged("Facility_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facility_Name {
            get {
                return this.Facility_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Facility_NameField, value) != true)) {
                    this.Facility_NameField = value;
                    this.RaisePropertyChanged("Facility_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Onwer_Approval_Number_Original {
            get {
                return this.Onwer_Approval_Number_OriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.Onwer_Approval_Number_OriginalField, value) != true)) {
                    this.Onwer_Approval_Number_OriginalField = value;
                    this.RaisePropertyChanged("Onwer_Approval_Number_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Owner_Approval_Date {
            get {
                return this.Owner_Approval_DateField;
            }
            set {
                if ((this.Owner_Approval_DateField.Equals(value) != true)) {
                    this.Owner_Approval_DateField = value;
                    this.RaisePropertyChanged("Owner_Approval_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Handling_Approved {
            get {
                return this.Owner_Handling_ApprovedField;
            }
            set {
                if ((this.Owner_Handling_ApprovedField.Equals(value) != true)) {
                    this.Owner_Handling_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Handling_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Labor_Approved {
            get {
                return this.Owner_Labor_ApprovedField;
            }
            set {
                if ((this.Owner_Labor_ApprovedField.Equals(value) != true)) {
                    this.Owner_Labor_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Labor_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Material_Approved {
            get {
                return this.Owner_Material_ApprovedField;
            }
            set {
                if ((this.Owner_Material_ApprovedField.Equals(value) != true)) {
                    this.Owner_Material_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Material_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Tax_Approved {
            get {
                return this.Owner_Tax_ApprovedField;
            }
            set {
                if ((this.Owner_Tax_ApprovedField.Equals(value) != true)) {
                    this.Owner_Tax_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Tax_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_Total_Approved {
            get {
                return this.Owner_Total_ApprovedField;
            }
            set {
                if ((this.Owner_Total_ApprovedField.Equals(value) != true)) {
                    this.Owner_Total_ApprovedField = value;
                    this.RaisePropertyChanged("Owner_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_handling_original {
            get {
                return this.Owner_total_handling_originalField;
            }
            set {
                if ((this.Owner_total_handling_originalField.Equals(value) != true)) {
                    this.Owner_total_handling_originalField = value;
                    this.RaisePropertyChanged("Owner_total_handling_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_labor_original {
            get {
                return this.Owner_total_labor_originalField;
            }
            set {
                if ((this.Owner_total_labor_originalField.Equals(value) != true)) {
                    this.Owner_total_labor_originalField = value;
                    this.RaisePropertyChanged("Owner_total_labor_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_material_original {
            get {
                return this.Owner_total_material_originalField;
            }
            set {
                if ((this.Owner_total_material_originalField.Equals(value) != true)) {
                    this.Owner_total_material_originalField = value;
                    this.RaisePropertyChanged("Owner_total_material_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_original {
            get {
                return this.Owner_total_originalField;
            }
            set {
                if ((this.Owner_total_originalField.Equals(value) != true)) {
                    this.Owner_total_originalField = value;
                    this.RaisePropertyChanged("Owner_total_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Owner_total_tax_original {
            get {
                return this.Owner_total_tax_originalField;
            }
            set {
                if ((this.Owner_total_tax_originalField.Equals(value) != true)) {
                    this.Owner_total_tax_originalField = value;
                    this.RaisePropertyChanged("Owner_total_tax_original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Repair_Complete_Reported {
            get {
                return this.Repair_Complete_ReportedField;
            }
            set {
                if ((this.Repair_Complete_ReportedField.Equals(value) != true)) {
                    this.Repair_Complete_ReportedField = value;
                    this.RaisePropertyChanged("Repair_Complete_Reported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Repair_Completed_Date {
            get {
                return this.Repair_Completed_DateField;
            }
            set {
                if ((this.Repair_Completed_DateField.Equals(value) != true)) {
                    this.Repair_Completed_DateField = value;
                    this.RaisePropertyChanged("Repair_Completed_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Revision_Number {
            get {
                return this.Revision_NumberField;
            }
            set {
                if ((this.Revision_NumberField.Equals(value) != true)) {
                    this.Revision_NumberField = value;
                    this.RaisePropertyChanged("Revision_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary_Size_Type {
            get {
                return this.Summary_Size_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Summary_Size_TypeField, value) != true)) {
                    this.Summary_Size_TypeField = value;
                    this.RaisePropertyChanged("Summary_Size_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surveyrequested {
            get {
                return this.SurveyrequestedField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyrequestedField, value) != true)) {
                    this.SurveyrequestedField = value;
                    this.RaisePropertyChanged("Surveyrequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_Approved {
            get {
                return this.User_Total_ApprovedField;
            }
            set {
                if ((this.User_Total_ApprovedField.Equals(value) != true)) {
                    this.User_Total_ApprovedField = value;
                    this.RaisePropertyChanged("User_Total_Approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_Original {
            get {
                return this.User_Total_OriginalField;
            }
            set {
                if ((this.User_Total_OriginalField.Equals(value) != true)) {
                    this.User_Total_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_handling_Original {
            get {
                return this.User_Total_handling_OriginalField;
            }
            set {
                if ((this.User_Total_handling_OriginalField.Equals(value) != true)) {
                    this.User_Total_handling_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_handling_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_material_Original {
            get {
                return this.User_Total_material_OriginalField;
            }
            set {
                if ((this.User_Total_material_OriginalField.Equals(value) != true)) {
                    this.User_Total_material_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_material_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_Total_tax_Original {
            get {
                return this.User_Total_tax_OriginalField;
            }
            set {
                if ((this.User_Total_tax_OriginalField.Equals(value) != true)) {
                    this.User_Total_tax_OriginalField = value;
                    this.RaisePropertyChanged("User_Total_tax_Original");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> User_total_labor_original {
            get {
                return this.User_total_labor_originalField;
            }
            set {
                if ((this.User_total_labor_originalField.Equals(value) != true)) {
                    this.User_total_labor_originalField = value;
                    this.RaisePropertyChanged("User_total_labor_original");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstLineItemAnalysi", Namespace="http://schemas.datacontract.org/2004/07/ManageHSUDDataService")]
    [System.SerializableAttribute()]
    public partial class EstLineItemAnalysi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> APPROVALDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BASECURRENCYCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPONENTCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CREATEDBYUSERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DAMAGECODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EQUIPMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EQUIPMENTTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ESTIMATEDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FACILITYCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FACILITYNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ISSURVEYREQUESTEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LABORCOSTBASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LABORHOURSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LABORRATEBASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LENGTHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LINEITEMNUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOCATIONCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATERIALCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MATERIALCOSTBASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORGANIZATIONTYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPAIRCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENDERESTIMATEIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SUMMARYSIZETYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TOTALBASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNITOFMEASUREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WIDTHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> APPROVALDATE {
            get {
                return this.APPROVALDATEField;
            }
            set {
                if ((this.APPROVALDATEField.Equals(value) != true)) {
                    this.APPROVALDATEField = value;
                    this.RaisePropertyChanged("APPROVALDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BASECURRENCYCODE {
            get {
                return this.BASECURRENCYCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.BASECURRENCYCODEField, value) != true)) {
                    this.BASECURRENCYCODEField = value;
                    this.RaisePropertyChanged("BASECURRENCYCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPONENTCODE {
            get {
                return this.COMPONENTCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPONENTCODEField, value) != true)) {
                    this.COMPONENTCODEField = value;
                    this.RaisePropertyChanged("COMPONENTCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CREATEDBYUSER {
            get {
                return this.CREATEDBYUSERField;
            }
            set {
                if ((object.ReferenceEquals(this.CREATEDBYUSERField, value) != true)) {
                    this.CREATEDBYUSERField = value;
                    this.RaisePropertyChanged("CREATEDBYUSER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DAMAGECODE {
            get {
                return this.DAMAGECODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DAMAGECODEField, value) != true)) {
                    this.DAMAGECODEField = value;
                    this.RaisePropertyChanged("DAMAGECODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EQUIPMENTID {
            get {
                return this.EQUIPMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EQUIPMENTIDField, value) != true)) {
                    this.EQUIPMENTIDField = value;
                    this.RaisePropertyChanged("EQUIPMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EQUIPMENTTYPE {
            get {
                return this.EQUIPMENTTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.EQUIPMENTTYPEField, value) != true)) {
                    this.EQUIPMENTTYPEField = value;
                    this.RaisePropertyChanged("EQUIPMENTTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ESTIMATEDATE {
            get {
                return this.ESTIMATEDATEField;
            }
            set {
                if ((this.ESTIMATEDATEField.Equals(value) != true)) {
                    this.ESTIMATEDATEField = value;
                    this.RaisePropertyChanged("ESTIMATEDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACILITYCODE {
            get {
                return this.FACILITYCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.FACILITYCODEField, value) != true)) {
                    this.FACILITYCODEField = value;
                    this.RaisePropertyChanged("FACILITYCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACILITYNAME {
            get {
                return this.FACILITYNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FACILITYNAMEField, value) != true)) {
                    this.FACILITYNAMEField = value;
                    this.RaisePropertyChanged("FACILITYNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ISSURVEYREQUESTED {
            get {
                return this.ISSURVEYREQUESTEDField;
            }
            set {
                if ((this.ISSURVEYREQUESTEDField.Equals(value) != true)) {
                    this.ISSURVEYREQUESTEDField = value;
                    this.RaisePropertyChanged("ISSURVEYREQUESTED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LABORCOSTBASE {
            get {
                return this.LABORCOSTBASEField;
            }
            set {
                if ((this.LABORCOSTBASEField.Equals(value) != true)) {
                    this.LABORCOSTBASEField = value;
                    this.RaisePropertyChanged("LABORCOSTBASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LABORHOURS {
            get {
                return this.LABORHOURSField;
            }
            set {
                if ((this.LABORHOURSField.Equals(value) != true)) {
                    this.LABORHOURSField = value;
                    this.RaisePropertyChanged("LABORHOURS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LABORRATEBASE {
            get {
                return this.LABORRATEBASEField;
            }
            set {
                if ((this.LABORRATEBASEField.Equals(value) != true)) {
                    this.LABORRATEBASEField = value;
                    this.RaisePropertyChanged("LABORRATEBASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LENGTH {
            get {
                return this.LENGTHField;
            }
            set {
                if ((this.LENGTHField.Equals(value) != true)) {
                    this.LENGTHField = value;
                    this.RaisePropertyChanged("LENGTH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LINEITEMNUMBER {
            get {
                return this.LINEITEMNUMBERField;
            }
            set {
                if ((this.LINEITEMNUMBERField.Equals(value) != true)) {
                    this.LINEITEMNUMBERField = value;
                    this.RaisePropertyChanged("LINEITEMNUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOCATIONCODE {
            get {
                return this.LOCATIONCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.LOCATIONCODEField, value) != true)) {
                    this.LOCATIONCODEField = value;
                    this.RaisePropertyChanged("LOCATIONCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERIALCODE {
            get {
                return this.MATERIALCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERIALCODEField, value) != true)) {
                    this.MATERIALCODEField = value;
                    this.RaisePropertyChanged("MATERIALCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MATERIALCOSTBASE {
            get {
                return this.MATERIALCOSTBASEField;
            }
            set {
                if ((this.MATERIALCOSTBASEField.Equals(value) != true)) {
                    this.MATERIALCOSTBASEField = value;
                    this.RaisePropertyChanged("MATERIALCOSTBASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORGANIZATIONTYPE {
            get {
                return this.ORGANIZATIONTYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.ORGANIZATIONTYPEField, value) != true)) {
                    this.ORGANIZATIONTYPEField = value;
                    this.RaisePropertyChanged("ORGANIZATIONTYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QUANTITY {
            get {
                return this.QUANTITYField;
            }
            set {
                if ((this.QUANTITYField.Equals(value) != true)) {
                    this.QUANTITYField = value;
                    this.RaisePropertyChanged("QUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPAIRCODE {
            get {
                return this.REPAIRCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.REPAIRCODEField, value) != true)) {
                    this.REPAIRCODEField = value;
                    this.RaisePropertyChanged("REPAIRCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENDERESTIMATEID {
            get {
                return this.SENDERESTIMATEIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SENDERESTIMATEIDField, value) != true)) {
                    this.SENDERESTIMATEIDField = value;
                    this.RaisePropertyChanged("SENDERESTIMATEID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SUMMARYSIZETYPE {
            get {
                return this.SUMMARYSIZETYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.SUMMARYSIZETYPEField, value) != true)) {
                    this.SUMMARYSIZETYPEField = value;
                    this.RaisePropertyChanged("SUMMARYSIZETYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TOTALBASE {
            get {
                return this.TOTALBASEField;
            }
            set {
                if ((this.TOTALBASEField.Equals(value) != true)) {
                    this.TOTALBASEField = value;
                    this.RaisePropertyChanged("TOTALBASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNITOFMEASURE {
            get {
                return this.UNITOFMEASUREField;
            }
            set {
                if ((object.ReferenceEquals(this.UNITOFMEASUREField, value) != true)) {
                    this.UNITOFMEASUREField = value;
                    this.RaisePropertyChanged("UNITOFMEASURE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WIDTH {
            get {
                return this.WIDTHField;
            }
            set {
                if ((this.WIDTHField.Equals(value) != true)) {
                    this.WIDTHField = value;
                    this.RaisePropertyChanged("WIDTH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageHSUDDataServiceReference.IManageHSUDDataService")]
    public interface IManageHSUDDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageHSUDDataService/GetData", ReplyAction="http://tempuri.org/IManageHSUDDataService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageHSUDDataService/HSUDDataSearch", ReplyAction="http://tempuri.org/IManageHSUDDataService/HSUDDataSearchResponse")]
        MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycle_ApprovalCanceled[] HSUDDataSearch(string EquipmentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageHSUDDataService/GetEstLifeCycle_ApprovalCanceledData", ReplyAction="http://tempuri.org/IManageHSUDDataService/GetEstLifeCycle_ApprovalCanceledDataRes" +
            "ponse")]
        MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycle_ApprovalCanceled[] GetEstLifeCycle_ApprovalCanceledData(string EquipmentNo, string EstimateNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageHSUDDataService/GetEstLifeCycleAnalysisData", ReplyAction="http://tempuri.org/IManageHSUDDataService/GetEstLifeCycleAnalysisDataResponse")]
        MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycleAnalysi[] GetEstLifeCycleAnalysisData(string EquipmentNo, string EstimateNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageHSUDDataService/GetEstLineItemAnalysisData", ReplyAction="http://tempuri.org/IManageHSUDDataService/GetEstLineItemAnalysisDataResponse")]
        MercPlusClient.ManageHSUDDataServiceReference.EstLineItemAnalysi[] GetEstLineItemAnalysisData(string EquipmentNo, string EstimateNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManageHSUDDataServiceChannel : MercPlusClient.ManageHSUDDataServiceReference.IManageHSUDDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageHSUDDataServiceClient : System.ServiceModel.ClientBase<MercPlusClient.ManageHSUDDataServiceReference.IManageHSUDDataService>, MercPlusClient.ManageHSUDDataServiceReference.IManageHSUDDataService {
        
        public ManageHSUDDataServiceClient() {
        }
        
        public ManageHSUDDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageHSUDDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageHSUDDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageHSUDDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycle_ApprovalCanceled[] HSUDDataSearch(string EquipmentNo) {
            return base.Channel.HSUDDataSearch(EquipmentNo);
        }
        
        public MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycle_ApprovalCanceled[] GetEstLifeCycle_ApprovalCanceledData(string EquipmentNo, string EstimateNo) {
            return base.Channel.GetEstLifeCycle_ApprovalCanceledData(EquipmentNo, EstimateNo);
        }
        
        public MercPlusClient.ManageHSUDDataServiceReference.EstLifeCycleAnalysi[] GetEstLifeCycleAnalysisData(string EquipmentNo, string EstimateNo) {
            return base.Channel.GetEstLifeCycleAnalysisData(EquipmentNo, EstimateNo);
        }
        
        public MercPlusClient.ManageHSUDDataServiceReference.EstLineItemAnalysi[] GetEstLineItemAnalysisData(string EquipmentNo, string EstimateNo) {
            return base.Channel.GetEstLineItemAnalysisData(EquipmentNo, EstimateNo);
        }
    }
}
