//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageHSUDDataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HSUDDataEntities : DbContext
    {
        public HSUDDataEntities()
            : base("name=HSUDDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EstLifeCycle_ApprovalCanceled> EstLifeCycle_ApprovalCanceled { get; set; }
        public DbSet<EstLifeCycleAnalysi> EstLifeCycleAnalysis { get; set; }
        public DbSet<EstLineItemAnalysi> EstLineItemAnalysis { get; set; }
    }
}
