//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageReportsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_MODE
    {
        public MESC1TS_MODE()
        {
            this.MESC1TS_CPH_EQP_LIMIT = new HashSet<MESC1TS_CPH_EQP_LIMIT>();
            this.MESC1TS_CUST_SHOP_MODE = new HashSet<MESC1TS_CUST_SHOP_MODE>();
            this.MESC1TS_EQMODE = new HashSet<MESC1TS_EQMODE>();
            this.MESC1TS_MANUAL_MODE = new HashSet<MESC1TS_MANUAL_MODE>();
            this.MESC1TS_NONSCODE = new HashSet<MESC1TS_NONSCODE>();
            this.MESC1TS_PREPTIME = new HashSet<MESC1TS_PREPTIME>();
            this.MESC1TS_REPAIR_CODE = new HashSet<MESC1TS_REPAIR_CODE>();
            this.MESC1TS_TRANSMIT = new HashSet<MESC1TS_TRANSMIT>();
            this.MESC1TS_WO = new HashSet<MESC1TS_WO>();
        }
    
        public string MODE { get; set; }
        public string MODE_DESC { get; set; }
        public string STANDARD_TIME_SW { get; set; }
        public string VALIDATION_SW { get; set; }
        public string MODE_ACTIVE_SW { get; set; }
        public string CHUSER { get; set; }
        public string MODE_IND { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_CPH_EQP_LIMIT> MESC1TS_CPH_EQP_LIMIT { get; set; }
        public virtual ICollection<MESC1TS_CUST_SHOP_MODE> MESC1TS_CUST_SHOP_MODE { get; set; }
        public virtual ICollection<MESC1TS_EQMODE> MESC1TS_EQMODE { get; set; }
        public virtual ICollection<MESC1TS_MANUAL_MODE> MESC1TS_MANUAL_MODE { get; set; }
        public virtual ICollection<MESC1TS_NONSCODE> MESC1TS_NONSCODE { get; set; }
        public virtual ICollection<MESC1TS_PREPTIME> MESC1TS_PREPTIME { get; set; }
        public virtual ICollection<MESC1TS_REPAIR_CODE> MESC1TS_REPAIR_CODE { get; set; }
        public virtual ICollection<MESC1TS_TRANSMIT> MESC1TS_TRANSMIT { get; set; }
        public virtual ICollection<MESC1TS_WO> MESC1TS_WO { get; set; }
    }
}
