//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageReportsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_WOREPAIR
    {
        public int WO_ID { get; set; }
        public string REPAIR_CD { get; set; }
        public Nullable<short> QTY_REPAIRS { get; set; }
        public Nullable<decimal> SHOP_MATERIAL_AMT { get; set; }
        public Nullable<decimal> CPH_MATERIAL_AMT { get; set; }
        public string CHUSER { get; set; }
        public Nullable<double> ACTUAL_MANH { get; set; }
        public string NONS_CD { get; set; }
        public string MODE { get; set; }
        public System.DateTime CHTS { get; set; }
        public string MANUAL_CD { get; set; }
        public string DAMAGE_CD { get; set; }
        public string REPAIR_LOC_CD { get; set; }
        public string TPI_CD { get; set; }
    
        public virtual MESC1TS_WO MESC1TS_WO { get; set; }
    }
}
