//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageReportsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_REFAUDIT
    {
        public int AUDIT_ID { get; set; }
        public string TAB_NAME { get; set; }
        public string UNIQUE_ID { get; set; }
        public string COL_NAME { get; set; }
        public string OLD_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public string CHUSER { get; set; }
        public Nullable<System.DateTime> CHTS { get; set; }
    }
}
