//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageReportsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_REGION
    {
        public MESC1TS_REGION()
        {
            this.MESC1TS_LOCATION = new HashSet<MESC1TS_LOCATION>();
        }
    
        public string REGION_CD { get; set; }
        public string REGION_DESC { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_LOCATION> MESC1TS_LOCATION { get; set; }
    }
}
