//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercCloseWO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_WOPART
    {
        public string PART_CD { get; set; }
        public string REPAIR_CD { get; set; }
        public Nullable<decimal> COST_CPH { get; set; }
        public int WO_ID { get; set; }
        public Nullable<decimal> COST_LOCAL { get; set; }
        public string CHUSER { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<double> QTY_PARTS { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_MASTER_PART MESC1TS_MASTER_PART { get; set; }
    }
}
