//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercCloseWO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_SHOP_LIMITS
    {
        public string SHOP_CD { get; set; }
        public string MODE { get; set; }
        public Nullable<decimal> REPAIR_AMT_LIMIT { get; set; }
        public Nullable<decimal> AUTO_APPROVE_LIMIT { get; set; }
        public Nullable<decimal> SHOP_MATERIAL_LIMIT { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_SHOP MESC1TS_SHOP { get; set; }
    }
}
