//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercCloseWO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_AUTHGROUP_USER
    {
        public int ACCESS_ID { get; set; }
        public int AUTHGROUP_ID { get; set; }
        public int USER_ID { get; set; }
        public string COLUMN_VALUE { get; set; }
    
        public virtual SEC_AUTHGROUP SEC_AUTHGROUP { get; set; }
        public virtual SEC_USER SEC_USER { get; set; }
    }
}
