//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixPartRepairs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_EQSTYPE
    {
        public string EQSTYPE { get; set; }
        public string COTYPE { get; set; }
        public string TYPE_DESC { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    }
}
