//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixPartRepairs
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_SUSPEND_CAT
    {
        public MESC1TS_SUSPEND_CAT()
        {
            this.MESC1TS_SUSPEND = new HashSet<MESC1TS_SUSPEND>();
            this.MESC1TS_WOREMARK = new HashSet<MESC1TS_WOREMARK>();
        }
    
        public int SUSPCAT_ID { get; set; }
        public string SUSPCAT_DESC { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_SUSPEND> MESC1TS_SUSPEND { get; set; }
        public virtual ICollection<MESC1TS_WOREMARK> MESC1TS_WOREMARK { get; set; }
    }
}
