//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_AUDITSTATUS_CODE
    {
        public short AUDIT_STATUS { get; set; }
        public string STATUS_DSC { get; set; }
    }
}
