//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_MANUFACTUR
    {
        public MESC1TS_MANUFACTUR()
        {
            this.MESC1TS_MASTER_PART = new HashSet<MESC1TS_MASTER_PART>();
            this.MESC1TS_MODEL = new HashSet<MESC1TS_MODEL>();
        }
    
        public string MANUFCTR { get; set; }
        public Nullable<double> DISCOUNT_PERCENT { get; set; }
        public string MANUFACTUR_NAME { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_MASTER_PART> MESC1TS_MASTER_PART { get; set; }
        public virtual ICollection<MESC1TS_MODEL> MESC1TS_MODEL { get; set; }
    }
}
