//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_RPRCODE_PART
    {
        public string REPAIR_CD { get; set; }
        public string MODE { get; set; }
        public string MANUAL_CD { get; set; }
        public string PART_CD { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
        public Nullable<int> MAX_PART_QTY { get; set; }
    
        public virtual MESC1TS_MASTER_PART MESC1TS_MASTER_PART { get; set; }
    }
}
