//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_XML_LOG
    {
        public long XML_ID { get; set; }
        public Nullable<System.DateTime> CRTS { get; set; }
        public string XML_TEXT { get; set; }
    }
}
