//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_AUDIT_HISTORY
    {
        public int WO_ID { get; set; }
        public string SHOP_CD { get; set; }
        public System.DateTime AUDIT_DATE { get; set; }
        public string AUDITOR { get; set; }
        public Nullable<int> AUDIT_RESULT { get; set; }
        public string VISIT_DESC { get; set; }
        public string VISIT_ID { get; set; }
        public string ARCHIVE_ID { get; set; }
        public string COMMENT { get; set; }
        public string CERTIFICATE_ID { get; set; }
        public string MERC_STATUS { get; set; }
        public string MERC_COMMENTS { get; set; }
        public Nullable<int> STATUS_CODE { get; set; }
        public Nullable<double> REPAIR_QUALITY { get; set; }
    }
}
