//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_FUNCTION
    {
        public int FUNCTION_ID { get; set; }
        public int ACTION_ID { get; set; }
        public string FUNCTION_NAME { get; set; }
    }
}
