//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class WO_VALIDATION
    {
        public string ROLES { get; set; }
        public int WOSTATUS { get; set; }
        public Nullable<int> REJECT { get; set; }
        public Nullable<int> ACCEPT { get; set; }
    }
}
