//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercDERTService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_PROCESS_IDENTIFIER
    {
        public int PROCESS_ID { get; set; }
        public string PROCESS_DESC { get; set; }
        public string PARAM_NAME { get; set; }
        public string PARAM_VALUE { get; set; }
    }
}
