//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercUserActiveChecker.ManageUserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ApproveAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChangeTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsUserActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLogInDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoccdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginFirstAndLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActiveStatus {
            get {
                return this.ActiveStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveStatusField, value) != true)) {
                    this.ActiveStatusField = value;
                    this.RaisePropertyChanged("ActiveStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ApproveAmount {
            get {
                return this.ApproveAmountField;
            }
            set {
                if ((this.ApproveAmountField.Equals(value) != true)) {
                    this.ApproveAmountField = value;
                    this.RaisePropertyChanged("ApproveAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthGroupName {
            get {
                return this.AuthGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthGroupNameField, value) != true)) {
                    this.AuthGroupNameField = value;
                    this.RaisePropertyChanged("AuthGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChangeTime {
            get {
                return this.ChangeTimeField;
            }
            set {
                if ((this.ChangeTimeField.Equals(value) != true)) {
                    this.ChangeTimeField = value;
                    this.RaisePropertyChanged("ChangeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeUser {
            get {
                return this.ChangeUserField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeUserField, value) != true)) {
                    this.ChangeUserField = value;
                    this.RaisePropertyChanged("ChangeUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsUserActive {
            get {
                return this.IsUserActiveField;
            }
            set {
                if ((this.IsUserActiveField.Equals(value) != true)) {
                    this.IsUserActiveField = value;
                    this.RaisePropertyChanged("IsUserActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogInDateTime {
            get {
                return this.LastLogInDateTimeField;
            }
            set {
                if ((this.LastLogInDateTimeField.Equals(value) != true)) {
                    this.LastLogInDateTimeField = value;
                    this.RaisePropertyChanged("LastLogInDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Loccd {
            get {
                return this.LoccdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoccdField, value) != true)) {
                    this.LoccdField = value;
                    this.RaisePropertyChanged("Loccd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginFirstAndLastName {
            get {
                return this.LoginFirstAndLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginFirstAndLastNameField, value) != true)) {
                    this.LoginFirstAndLastNameField = value;
                    this.RaisePropertyChanged("LoginFirstAndLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ChangeTimeConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChangeUserConField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeAndDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryGeoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNotFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MercUserActiveChecker.ManageUserServiceReference.ErrMessage ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RepairLimitAdjFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowDivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChangeTimeCon {
            get {
                return this.ChangeTimeConField;
            }
            set {
                if ((this.ChangeTimeConField.Equals(value) != true)) {
                    this.ChangeTimeConField = value;
                    this.RaisePropertyChanged("ChangeTimeCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeUserCon {
            get {
                return this.ChangeUserConField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeUserConField, value) != true)) {
                    this.ChangeUserConField = value;
                    this.RaisePropertyChanged("ChangeUserCon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCodeAndDescription {
            get {
                return this.CountryCodeAndDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeAndDescriptionField, value) != true)) {
                    this.CountryCodeAndDescriptionField = value;
                    this.RaisePropertyChanged("CountryCodeAndDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryDescription {
            get {
                return this.CountryDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryDescriptionField, value) != true)) {
                    this.CountryDescriptionField = value;
                    this.RaisePropertyChanged("CountryDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryGeoID {
            get {
                return this.CountryGeoIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryGeoIDField, value) != true)) {
                    this.CountryGeoIDField = value;
                    this.RaisePropertyChanged("CountryGeoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryNotFound {
            get {
                return this.CountryNotFoundField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNotFoundField, value) != true)) {
                    this.CountryNotFoundField = value;
                    this.RaisePropertyChanged("CountryNotFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MercUserActiveChecker.ManageUserServiceReference.ErrMessage ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> RepairLimitAdjFactor {
            get {
                return this.RepairLimitAdjFactorField;
            }
            set {
                if ((this.RepairLimitAdjFactorField.Equals(value) != true)) {
                    this.RepairLimitAdjFactorField = value;
                    this.RaisePropertyChanged("RepairLimitAdjFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowDiv {
            get {
                return this.ShowDivField;
            }
            set {
                if ((this.ShowDivField.Equals(value) != true)) {
                    this.ShowDivField = value;
                    this.RaisePropertyChanged("ShowDiv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrMessage", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class ErrMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorNo {
            get {
                return this.ErrorNoField;
            }
            set {
                if ((this.ErrorNoField.Equals(value) != true)) {
                    this.ErrorNoField = value;
                    this.RaisePropertyChanged("ErrorNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorType {
            get {
                return this.ErrorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorTypeField, value) != true)) {
                    this.ErrorTypeField = value;
                    this.RaisePropertyChanged("ErrorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssignAuthGroup", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class AssignAuthGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListItem {
            get {
                return this.ListItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ListItemField, value) != true)) {
                    this.ListItemField = value;
                    this.RaisePropertyChanged("ListItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueItem {
            get {
                return this.ValueItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueItemField, value) != true)) {
                    this.ValueItemField = value;
                    this.RaisePropertyChanged("ValueItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableAssignAuthGroup", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class AvailableAssignAuthGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListItem {
            get {
                return this.ListItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ListItemField, value) != true)) {
                    this.ListItemField = value;
                    this.RaisePropertyChanged("ListItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueItem {
            get {
                return this.ValueItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueItemField, value) != true)) {
                    this.ValueItemField = value;
                    this.RaisePropertyChanged("ValueItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecAuthGroup", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class SecAuthGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentAuthGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReadOnlySwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthGroupId {
            get {
                return this.AuthGroupIdField;
            }
            set {
                if ((this.AuthGroupIdField.Equals(value) != true)) {
                    this.AuthGroupIdField = value;
                    this.RaisePropertyChanged("AuthGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthGroupName {
            get {
                return this.AuthGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthGroupNameField, value) != true)) {
                    this.AuthGroupNameField = value;
                    this.RaisePropertyChanged("AuthGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnDesc {
            get {
                return this.ColumnDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnDescField, value) != true)) {
                    this.ColumnDescField = value;
                    this.RaisePropertyChanged("ColumnDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentAuthGroupId {
            get {
                return this.ParentAuthGroupIdField;
            }
            set {
                if ((this.ParentAuthGroupIdField.Equals(value) != true)) {
                    this.ParentAuthGroupIdField = value;
                    this.RaisePropertyChanged("ParentAuthGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReadOnlySw {
            get {
                return this.ReadOnlySwField;
            }
            set {
                if ((object.ReferenceEquals(this.ReadOnlySwField, value) != true)) {
                    this.ReadOnlySwField = value;
                    this.RaisePropertyChanged("ReadOnlySw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecAuthGroupUserInfo", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class SecAuthGroupUserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColumnValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessId {
            get {
                return this.AccessIdField;
            }
            set {
                if ((this.AccessIdField.Equals(value) != true)) {
                    this.AccessIdField = value;
                    this.RaisePropertyChanged("AccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthGroupId {
            get {
                return this.AuthGroupIdField;
            }
            set {
                if ((this.AuthGroupIdField.Equals(value) != true)) {
                    this.AuthGroupIdField = value;
                    this.RaisePropertyChanged("AuthGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthGroupName {
            get {
                return this.AuthGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthGroupNameField, value) != true)) {
                    this.AuthGroupNameField = value;
                    this.RaisePropertyChanged("AuthGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnDesc {
            get {
                return this.ColumnDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnDescField, value) != true)) {
                    this.ColumnDescField = value;
                    this.RaisePropertyChanged("ColumnDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnName {
            get {
                return this.ColumnNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnNameField, value) != true)) {
                    this.ColumnNameField = value;
                    this.RaisePropertyChanged("ColumnName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColumnValue {
            get {
                return this.ColumnValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnValueField, value) != true)) {
                    this.ColumnValueField = value;
                    this.RaisePropertyChanged("ColumnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecWebSite", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class SecWebSite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebSiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebSiteId {
            get {
                return this.WebSiteIdField;
            }
            set {
                if ((this.WebSiteIdField.Equals(value) != true)) {
                    this.WebSiteIdField = value;
                    this.RaisePropertyChanged("WebSiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSiteName {
            get {
                return this.WebSiteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteNameField, value) != true)) {
                    this.WebSiteNameField = value;
                    this.RaisePropertyChanged("WebSiteName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecWebPage", Namespace="http://schemas.datacontract.org/2004/07/MercPlusLibrary")]
    [System.SerializableAttribute()]
    public partial class SecWebPage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebPageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebPageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WebSiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebPageId {
            get {
                return this.WebPageIdField;
            }
            set {
                if ((this.WebPageIdField.Equals(value) != true)) {
                    this.WebPageIdField = value;
                    this.RaisePropertyChanged("WebPageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebPageName {
            get {
                return this.WebPageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebPageNameField, value) != true)) {
                    this.WebPageNameField = value;
                    this.RaisePropertyChanged("WebPageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WebSiteId {
            get {
                return this.WebSiteIdField;
            }
            set {
                if ((this.WebSiteIdField.Equals(value) != true)) {
                    this.WebSiteIdField = value;
                    this.RaisePropertyChanged("WebSiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManageUserServiceReference.IManageUser")]
    public interface IManageUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/isUserExistInDb", ReplyAction="http://tempuri.org/IManageUser/isUserExistInDbResponse")]
        bool isUserExistInDb(string Login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/isUserExistInDb", ReplyAction="http://tempuri.org/IManageUser/isUserExistInDbResponse")]
        System.Threading.Tasks.Task<bool> isUserExistInDbAsync(string Login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AddUser", ReplyAction="http://tempuri.org/IManageUser/AddUserResponse")]
        MercUserActiveChecker.ManageUserServiceReference.AddUserResponse AddUser(MercUserActiveChecker.ManageUserServiceReference.AddUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AddUser", ReplyAction="http://tempuri.org/IManageUser/AddUserResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AddUserResponse> AddUserAsync(MercUserActiveChecker.ManageUserServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetCountryList", ReplyAction="http://tempuri.org/IManageUser/GetCountryListResponse")]
        MercUserActiveChecker.ManageUserServiceReference.Country[] GetCountryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetCountryList", ReplyAction="http://tempuri.org/IManageUser/GetCountryListResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.Country[]> GetCountryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateUser", ReplyAction="http://tempuri.org/IManageUser/UpdateUserResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UpdateUserResponse UpdateUser(MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateUser", ReplyAction="http://tempuri.org/IManageUser/UpdateUserResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateUserResponse> UpdateUserAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateUserActiveStatus", ReplyAction="http://tempuri.org/IManageUser/UpdateUserActiveStatusResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusResponse UpdateUserActiveStatus(MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateUserActiveStatus", ReplyAction="http://tempuri.org/IManageUser/UpdateUserActiveStatusResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusResponse> UpdateUserActiveStatusAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/DeleteUser", ReplyAction="http://tempuri.org/IManageUser/DeleteUserResponse")]
        MercUserActiveChecker.ManageUserServiceReference.DeleteUserResponse DeleteUser(MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/DeleteUser", ReplyAction="http://tempuri.org/IManageUser/DeleteUserResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.DeleteUserResponse> DeleteUserAsync(MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/DeleteUserDataAccessByUserId", ReplyAction="http://tempuri.org/IManageUser/DeleteUserDataAccessByUserIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdResponse DeleteUserDataAccessByUserId(MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/DeleteUserDataAccessByUserId", ReplyAction="http://tempuri.org/IManageUser/DeleteUserDataAccessByUserIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdResponse> DeleteUserDataAccessByUserIdAsync(MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserListOfACountry", ReplyAction="http://tempuri.org/IManageUser/GetUserListOfACountryResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserListOfACountry(string CountryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserListOfACountry", ReplyAction="http://tempuri.org/IManageUser/GetUserListOfACountryResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserListOfACountryAsync(string CountryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByUserId", ReplyAction="http://tempuri.org/IManageUser/GetUserByUserIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByUserId(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByUserId", ReplyAction="http://tempuri.org/IManageUser/GetUserByUserIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByUserIdAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByEmailId", ReplyAction="http://tempuri.org/IManageUser/GetUserByEmailIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByEmailId(string EmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByEmailId", ReplyAction="http://tempuri.org/IManageUser/GetUserByEmailIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByEmailIdAsync(string EmailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByLoginId", ReplyAction="http://tempuri.org/IManageUser/GetUserByLoginIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByLoginId(string LoginId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetUserByLoginId", ReplyAction="http://tempuri.org/IManageUser/GetUserByLoginIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByLoginIdAsync(string LoginId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/IsLocationCodeExist", ReplyAction="http://tempuri.org/IManageUser/IsLocationCodeExistResponse")]
        bool IsLocationCodeExist(string LocCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/IsLocationCodeExist", ReplyAction="http://tempuri.org/IManageUser/IsLocationCodeExistResponse")]
        System.Threading.Tasks.Task<bool> IsLocationCodeExistAsync(string LocCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AvailablePermissions", ReplyAction="http://tempuri.org/IManageUser/AvailablePermissionsResponse")]
        MercUserActiveChecker.ManageUserServiceReference.AssignAuthGroup[] AvailablePermissions(int UserId, int AuthGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AvailablePermissions", ReplyAction="http://tempuri.org/IManageUser/AvailablePermissionsResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AssignAuthGroup[]> AvailablePermissionsAsync(int UserId, int AuthGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AvailablePermissionsByFilter", ReplyAction="http://tempuri.org/IManageUser/AvailablePermissionsByFilterResponse")]
        MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterResponse AvailablePermissionsByFilter(MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AvailablePermissionsByFilter", ReplyAction="http://tempuri.org/IManageUser/AvailablePermissionsByFilterResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterResponse> AvailablePermissionsByFilterAsync(MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupList", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupListResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[] GetAuthGroupList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupList", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupListResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[]> GetAuthGroupListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupByAuthgroupId", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupByAuthgroupIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[] GetAuthGroupByAuthgroupId(int AuthGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupByAuthgroupId", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupByAuthgroupIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[]> GetAuthGroupByAuthgroupIdAsync(int AuthGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupByUserID", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupByUserIDResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecAuthGroupUserInfo[] GetAuthGroupByUserID(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupByUserID", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupByUserIDResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroupUserInfo[]> GetAuthGroupByUserIDAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/InsertUserDataAccess", ReplyAction="http://tempuri.org/IManageUser/InsertUserDataAccessResponse")]
        MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessResponse InsertUserDataAccess(MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/InsertUserDataAccess", ReplyAction="http://tempuri.org/IManageUser/InsertUserDataAccessResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessResponse> InsertUserDataAccessAsync(MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetWebPageList", ReplyAction="http://tempuri.org/IManageUser/GetWebPageListResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecWebSite[] GetWebPageList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetWebPageList", ReplyAction="http://tempuri.org/IManageUser/GetWebPageListResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebSite[]> GetWebPageListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetWebpageListByWebsiteId", ReplyAction="http://tempuri.org/IManageUser/GetWebpageListByWebsiteIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecWebSite[] GetWebpageListByWebsiteId(int WebSiteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetWebpageListByWebsiteId", ReplyAction="http://tempuri.org/IManageUser/GetWebpageListByWebsiteIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebSite[]> GetWebpageListByWebsiteIdAsync(int WebSiteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupWebpageAccessById", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupWebpageAccessByIdResponse")]
        MercUserActiveChecker.ManageUserServiceReference.SecWebPage[] GetAuthGroupWebpageAccessById(int WebSiteId, int AuthId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/GetAuthGroupWebpageAccessById", ReplyAction="http://tempuri.org/IManageUser/GetAuthGroupWebpageAccessByIdResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebPage[]> GetAuthGroupWebpageAccessByIdAsync(int WebSiteId, int AuthId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateWebPagePermissions", ReplyAction="http://tempuri.org/IManageUser/UpdateWebPagePermissionsResponse")]
        MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsResponse UpdateWebPagePermissions(MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/UpdateWebPagePermissions", ReplyAction="http://tempuri.org/IManageUser/UpdateWebPagePermissionsResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsResponse> UpdateWebPagePermissionsAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AddAllCluster", ReplyAction="http://tempuri.org/IManageUser/AddAllClusterResponse")]
        MercUserActiveChecker.ManageUserServiceReference.AddAllClusterResponse AddAllCluster(MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManageUser/AddAllCluster", ReplyAction="http://tempuri.org/IManageUser/AddAllClusterResponse")]
        System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AddAllClusterResponse> AddAllClusterAsync(MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient) {
            this.UserInfoFromClient = UserInfoFromClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(bool AddUserResult, string Msg) {
            this.AddUserResult = AddUserResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient) {
            this.UserInfoFromClient = UserInfoFromClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(bool UpdateUserResult, string Msg) {
            this.UpdateUserResult = UpdateUserResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserActiveStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserActiveStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int day;
        
        public UpdateUserActiveStatusRequest() {
        }
        
        public UpdateUserActiveStatusRequest(int day) {
            this.day = day;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateUserActiveStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateUserActiveStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateUserActiveStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public UpdateUserActiveStatusResponse() {
        }
        
        public UpdateUserActiveStatusResponse(bool UpdateUserActiveStatusResult, string Msg) {
            this.UpdateUserActiveStatusResult = UpdateUserActiveStatusResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserToBeDeleted;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(int UserToBeDeleted) {
            this.UserToBeDeleted = UserToBeDeleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(bool DeleteUserResult, string Msg) {
            this.DeleteUserResult = DeleteUserResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUserDataAccessByUserId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteUserDataAccessByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserToBeDeleted;
        
        public DeleteUserDataAccessByUserIdRequest() {
        }
        
        public DeleteUserDataAccessByUserIdRequest(int UserToBeDeleted) {
            this.UserToBeDeleted = UserToBeDeleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteUserDataAccessByUserIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteUserDataAccessByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteUserDataAccessByUserIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public DeleteUserDataAccessByUserIdResponse() {
        }
        
        public DeleteUserDataAccessByUserIdResponse(bool DeleteUserDataAccessByUserIdResult, string Msg) {
            this.DeleteUserDataAccessByUserIdResult = DeleteUserDataAccessByUserIdResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvailablePermissionsByFilter", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AvailablePermissionsByFilterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AuthGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SD;
        
        public AvailablePermissionsByFilterRequest() {
        }
        
        public AvailablePermissionsByFilterRequest(int UserId, int AuthGroupId, string SD) {
            this.UserId = UserId;
            this.AuthGroupId = AuthGroupId;
            this.SD = SD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AvailablePermissionsByFilterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AvailablePermissionsByFilterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MercUserActiveChecker.ManageUserServiceReference.AvailableAssignAuthGroup[] AvailablePermissionsByFilterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AvailablePermissionCount;
        
        public AvailablePermissionsByFilterResponse() {
        }
        
        public AvailablePermissionsByFilterResponse(MercUserActiveChecker.ManageUserServiceReference.AvailableAssignAuthGroup[] AvailablePermissionsByFilterResult, int AvailablePermissionCount) {
            this.AvailablePermissionsByFilterResult = AvailablePermissionsByFilterResult;
            this.AvailablePermissionCount = AvailablePermissionCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertUserDataAccess", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertUserDataAccessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SelectedActivePermission;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int AuthorisationGroupId;
        
        public InsertUserDataAccessRequest() {
        }
        
        public InsertUserDataAccessRequest(string SelectedActivePermission, int UserId, int AuthorisationGroupId) {
            this.SelectedActivePermission = SelectedActivePermission;
            this.UserId = UserId;
            this.AuthorisationGroupId = AuthorisationGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertUserDataAccessResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertUserDataAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertUserDataAccessResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public InsertUserDataAccessResponse() {
        }
        
        public InsertUserDataAccessResponse(bool InsertUserDataAccessResult, string Msg) {
            this.InsertUserDataAccessResult = InsertUserDataAccessResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWebPagePermissions", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWebPagePermissionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SelectedWebSitePermissions;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AuthorisationGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int WebpageId;
        
        public UpdateWebPagePermissionsRequest() {
        }
        
        public UpdateWebPagePermissionsRequest(string SelectedWebSitePermissions, int AuthorisationGroupId, int WebpageId) {
            this.SelectedWebSitePermissions = SelectedWebSitePermissions;
            this.AuthorisationGroupId = AuthorisationGroupId;
            this.WebpageId = WebpageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWebPagePermissionsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateWebPagePermissionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateWebPagePermissionsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public UpdateWebPagePermissionsResponse() {
        }
        
        public UpdateWebPagePermissionsResponse(bool UpdateWebPagePermissionsResult, string Msg) {
            this.UpdateWebPagePermissionsResult = UpdateWebPagePermissionsResult;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAllCluster", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAllClusterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int AuthorisationGroupId;
        
        public AddAllClusterRequest() {
        }
        
        public AddAllClusterRequest(int UserId, int AuthorisationGroupId) {
            this.UserId = UserId;
            this.AuthorisationGroupId = AuthorisationGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAllClusterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAllClusterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddAllClusterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Msg;
        
        public AddAllClusterResponse() {
        }
        
        public AddAllClusterResponse(bool AddAllClusterResult, string Msg) {
            this.AddAllClusterResult = AddAllClusterResult;
            this.Msg = Msg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManageUserChannel : MercUserActiveChecker.ManageUserServiceReference.IManageUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManageUserClient : System.ServiceModel.ClientBase<MercUserActiveChecker.ManageUserServiceReference.IManageUser>, MercUserActiveChecker.ManageUserServiceReference.IManageUser {
        
        public ManageUserClient() {
        }
        
        public ManageUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManageUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManageUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isUserExistInDb(string Login) {
            return base.Channel.isUserExistInDb(Login);
        }
        
        public System.Threading.Tasks.Task<bool> isUserExistInDbAsync(string Login) {
            return base.Channel.isUserExistInDbAsync(Login);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.AddUserResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.AddUser(MercUserActiveChecker.ManageUserServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public bool AddUser(MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.AddUserRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.AddUserRequest();
            inValue.UserInfoFromClient = UserInfoFromClient;
            MercUserActiveChecker.ManageUserServiceReference.AddUserResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).AddUser(inValue);
            Msg = retVal.Msg;
            return retVal.AddUserResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AddUserResponse> AddUserAsync(MercUserActiveChecker.ManageUserServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.Country[] GetCountryList() {
            return base.Channel.GetCountryList();
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.Country[]> GetCountryListAsync() {
            return base.Channel.GetCountryListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.UpdateUserResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.UpdateUser(MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public bool UpdateUser(MercUserActiveChecker.ManageUserServiceReference.UserInfo UserInfoFromClient, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest();
            inValue.UserInfoFromClient = UserInfoFromClient;
            MercUserActiveChecker.ManageUserServiceReference.UpdateUserResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).UpdateUser(inValue);
            Msg = retVal.Msg;
            return retVal.UpdateUserResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateUserResponse> UpdateUserAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.UpdateUserActiveStatus(MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest request) {
            return base.Channel.UpdateUserActiveStatus(request);
        }
        
        public bool UpdateUserActiveStatus(int day, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest();
            inValue.day = day;
            MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).UpdateUserActiveStatus(inValue);
            Msg = retVal.Msg;
            return retVal.UpdateUserActiveStatusResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusResponse> UpdateUserActiveStatusAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateUserActiveStatusRequest request) {
            return base.Channel.UpdateUserActiveStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.DeleteUserResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.DeleteUser(MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public bool DeleteUser(int UserToBeDeleted, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest();
            inValue.UserToBeDeleted = UserToBeDeleted;
            MercUserActiveChecker.ManageUserServiceReference.DeleteUserResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).DeleteUser(inValue);
            Msg = retVal.Msg;
            return retVal.DeleteUserResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.DeleteUserResponse> DeleteUserAsync(MercUserActiveChecker.ManageUserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.DeleteUserDataAccessByUserId(MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest request) {
            return base.Channel.DeleteUserDataAccessByUserId(request);
        }
        
        public bool DeleteUserDataAccessByUserId(int UserToBeDeleted, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest();
            inValue.UserToBeDeleted = UserToBeDeleted;
            MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).DeleteUserDataAccessByUserId(inValue);
            Msg = retVal.Msg;
            return retVal.DeleteUserDataAccessByUserIdResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdResponse> DeleteUserDataAccessByUserIdAsync(MercUserActiveChecker.ManageUserServiceReference.DeleteUserDataAccessByUserIdRequest request) {
            return base.Channel.DeleteUserDataAccessByUserIdAsync(request);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserListOfACountry(string CountryId) {
            return base.Channel.GetUserListOfACountry(CountryId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserListOfACountryAsync(string CountryId) {
            return base.Channel.GetUserListOfACountryAsync(CountryId);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByUserId(int UserId) {
            return base.Channel.GetUserByUserId(UserId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByUserIdAsync(int UserId) {
            return base.Channel.GetUserByUserIdAsync(UserId);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByEmailId(string EmailId) {
            return base.Channel.GetUserByEmailId(EmailId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByEmailIdAsync(string EmailId) {
            return base.Channel.GetUserByEmailIdAsync(EmailId);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.UserInfo[] GetUserByLoginId(string LoginId) {
            return base.Channel.GetUserByLoginId(LoginId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UserInfo[]> GetUserByLoginIdAsync(string LoginId) {
            return base.Channel.GetUserByLoginIdAsync(LoginId);
        }
        
        public bool IsLocationCodeExist(string LocCode) {
            return base.Channel.IsLocationCodeExist(LocCode);
        }
        
        public System.Threading.Tasks.Task<bool> IsLocationCodeExistAsync(string LocCode) {
            return base.Channel.IsLocationCodeExistAsync(LocCode);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.AssignAuthGroup[] AvailablePermissions(int UserId, int AuthGroupId) {
            return base.Channel.AvailablePermissions(UserId, AuthGroupId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AssignAuthGroup[]> AvailablePermissionsAsync(int UserId, int AuthGroupId) {
            return base.Channel.AvailablePermissionsAsync(UserId, AuthGroupId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.AvailablePermissionsByFilter(MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest request) {
            return base.Channel.AvailablePermissionsByFilter(request);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.AvailableAssignAuthGroup[] AvailablePermissionsByFilter(int UserId, int AuthGroupId, string SD, out int AvailablePermissionCount) {
            MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest();
            inValue.UserId = UserId;
            inValue.AuthGroupId = AuthGroupId;
            inValue.SD = SD;
            MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).AvailablePermissionsByFilter(inValue);
            AvailablePermissionCount = retVal.AvailablePermissionCount;
            return retVal.AvailablePermissionsByFilterResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterResponse> AvailablePermissionsByFilterAsync(MercUserActiveChecker.ManageUserServiceReference.AvailablePermissionsByFilterRequest request) {
            return base.Channel.AvailablePermissionsByFilterAsync(request);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[] GetAuthGroupList() {
            return base.Channel.GetAuthGroupList();
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[]> GetAuthGroupListAsync() {
            return base.Channel.GetAuthGroupListAsync();
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[] GetAuthGroupByAuthgroupId(int AuthGroupId) {
            return base.Channel.GetAuthGroupByAuthgroupId(AuthGroupId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroup[]> GetAuthGroupByAuthgroupIdAsync(int AuthGroupId) {
            return base.Channel.GetAuthGroupByAuthgroupIdAsync(AuthGroupId);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecAuthGroupUserInfo[] GetAuthGroupByUserID(int UserId) {
            return base.Channel.GetAuthGroupByUserID(UserId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecAuthGroupUserInfo[]> GetAuthGroupByUserIDAsync(int UserId) {
            return base.Channel.GetAuthGroupByUserIDAsync(UserId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.InsertUserDataAccess(MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest request) {
            return base.Channel.InsertUserDataAccess(request);
        }
        
        public bool InsertUserDataAccess(string SelectedActivePermission, int UserId, int AuthorisationGroupId, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest();
            inValue.SelectedActivePermission = SelectedActivePermission;
            inValue.UserId = UserId;
            inValue.AuthorisationGroupId = AuthorisationGroupId;
            MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).InsertUserDataAccess(inValue);
            Msg = retVal.Msg;
            return retVal.InsertUserDataAccessResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessResponse> InsertUserDataAccessAsync(MercUserActiveChecker.ManageUserServiceReference.InsertUserDataAccessRequest request) {
            return base.Channel.InsertUserDataAccessAsync(request);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecWebSite[] GetWebPageList() {
            return base.Channel.GetWebPageList();
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebSite[]> GetWebPageListAsync() {
            return base.Channel.GetWebPageListAsync();
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecWebSite[] GetWebpageListByWebsiteId(int WebSiteId) {
            return base.Channel.GetWebpageListByWebsiteId(WebSiteId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebSite[]> GetWebpageListByWebsiteIdAsync(int WebSiteId) {
            return base.Channel.GetWebpageListByWebsiteIdAsync(WebSiteId);
        }
        
        public MercUserActiveChecker.ManageUserServiceReference.SecWebPage[] GetAuthGroupWebpageAccessById(int WebSiteId, int AuthId) {
            return base.Channel.GetAuthGroupWebpageAccessById(WebSiteId, AuthId);
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.SecWebPage[]> GetAuthGroupWebpageAccessByIdAsync(int WebSiteId, int AuthId) {
            return base.Channel.GetAuthGroupWebpageAccessByIdAsync(WebSiteId, AuthId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.UpdateWebPagePermissions(MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest request) {
            return base.Channel.UpdateWebPagePermissions(request);
        }
        
        public bool UpdateWebPagePermissions(string SelectedWebSitePermissions, int AuthorisationGroupId, int WebpageId, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest();
            inValue.SelectedWebSitePermissions = SelectedWebSitePermissions;
            inValue.AuthorisationGroupId = AuthorisationGroupId;
            inValue.WebpageId = WebpageId;
            MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).UpdateWebPagePermissions(inValue);
            Msg = retVal.Msg;
            return retVal.UpdateWebPagePermissionsResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsResponse> UpdateWebPagePermissionsAsync(MercUserActiveChecker.ManageUserServiceReference.UpdateWebPagePermissionsRequest request) {
            return base.Channel.UpdateWebPagePermissionsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MercUserActiveChecker.ManageUserServiceReference.AddAllClusterResponse MercUserActiveChecker.ManageUserServiceReference.IManageUser.AddAllCluster(MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest request) {
            return base.Channel.AddAllCluster(request);
        }
        
        public bool AddAllCluster(int UserId, int AuthorisationGroupId, out string Msg) {
            MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest inValue = new MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest();
            inValue.UserId = UserId;
            inValue.AuthorisationGroupId = AuthorisationGroupId;
            MercUserActiveChecker.ManageUserServiceReference.AddAllClusterResponse retVal = ((MercUserActiveChecker.ManageUserServiceReference.IManageUser)(this)).AddAllCluster(inValue);
            Msg = retVal.Msg;
            return retVal.AddAllClusterResult;
        }
        
        public System.Threading.Tasks.Task<MercUserActiveChecker.ManageUserServiceReference.AddAllClusterResponse> AddAllClusterAsync(MercUserActiveChecker.ManageUserServiceReference.AddAllClusterRequest request) {
            return base.Channel.AddAllClusterAsync(request);
        }
    }
}
