//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageWorkOrderService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_PAYAGENT_VENDOR
    {
        public string PAYAGENT_CD { get; set; }
        public string VENDOR_CD { get; set; }
        public string LOCAL_ACCOUNT_CD { get; set; }
        public string SUPPLIER_CD { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual MESC1TS_PAYAGENT MESC1TS_PAYAGENT { get; set; }
        public virtual MESC1TS_VENDOR MESC1TS_VENDOR { get; set; }
    }
}
