//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageWorkOrderService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_GRADE
    {
        public MESC1TS_GRADE()
        {
            this.MESC1TS_GRADERELATION = new HashSet<MESC1TS_GRADERELATION>();
            this.MESC1TS_GRADESTS = new HashSet<MESC1TS_GRADESTS>();
        }
    
        public int GRADE_ID { get; set; }
        public string GRADECODE { get; set; }
        public string GRADE_DESC { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
    
        public virtual ICollection<MESC1TS_GRADERELATION> MESC1TS_GRADERELATION { get; set; }
        public virtual ICollection<MESC1TS_GRADESTS> MESC1TS_GRADESTS { get; set; }
    }
}
