//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageWorkOrderService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_GRADECONTAINER
    {
        public int GC_ID { get; set; }
        public string EQPNO { get; set; }
        public Nullable<int> WO_ID { get; set; }
        public string CURRENTLOC { get; set; }
        public string GRADECODE { get; set; }
        public string GRADECODE_NEW { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> MODIFIEDON { get; set; }
    }
}
