//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMasterDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_WOREMARK
    {
        public int WOREMARK_ID { get; set; }
        public int WO_ID { get; set; }
        public System.DateTime CRTS { get; set; }
        public string REMARK_TYPE { get; set; }
        public Nullable<System.DateTime> XMIT_DTE { get; set; }
        public string CHUSER { get; set; }
        public Nullable<int> SUSPCAT_ID { get; set; }
        public string REMARK { get; set; }
    
        public virtual MESC1TS_SUSPEND_CAT MESC1TS_SUSPEND_CAT { get; set; }
    }
}
