//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMasterDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_RPRCODE_EXCLU
    {
        public string REPAIR_CD { get; set; }
        public string EXCLU_REPAIR_CD { get; set; }
        public string MODE { get; set; }
        public string MANUAL_CD { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    }
}
