//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMasterDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_AUTHGROUP_FUNCTION
    {
        public int AUTHGROUP_ID { get; set; }
        public int FUNCTION_ID { get; set; }
    
        public virtual SEC_AUTHGROUP SEC_AUTHGROUP { get; set; }
    }
}
