//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageMasterDataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USER
    {
        public SEC_USER()
        {
            this.SEC_AUTHGROUP_USER = new HashSet<SEC_AUTHGROUP_USER>();
        }
    
        public int USER_ID { get; set; }
        public string LOGIN { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string COMPANY { get; set; }
        public string LOC_CD { get; set; }
        public string ACTIVE_STATUS { get; set; }
        public Nullable<decimal> APPROVAL_AMOUNT { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public string EmailId { get; set; }
    
        public virtual MESC1TS_LOCATION MESC1TS_LOCATION { get; set; }
        public virtual ICollection<SEC_AUTHGROUP_USER> SEC_AUTHGROUP_USER { get; set; }
    }
}
