//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercWOApprovalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESC1TS_PARTS_GROUP
    {
        public MESC1TS_PARTS_GROUP()
        {
            this.MESC1TS_MASTER_PART = new HashSet<MESC1TS_MASTER_PART>();
        }
    
        public string PARTS_GROUP_CD { get; set; }
        public string PARTS_GROUP_DESC { get; set; }
        public string REMARKS { get; set; }
        public string PARTS_GROUP_ACTIVE_SW { get; set; }
        public string CHUSER { get; set; }
        public System.DateTime CHTS { get; set; }
    
        public virtual ICollection<MESC1TS_MASTER_PART> MESC1TS_MASTER_PART { get; set; }
    }
}
