//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercPlusClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMerc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMerc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MercPlusClient.ResourceMerc", typeof(ResourceMerc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %% unsuccessful..
        /// </summary>
        internal static string ACTIONFAILED {
            get {
                return ResourceManager.GetString("ACTIONFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %% successful..
        /// </summary>
        internal static string ACTIONSUCCESS {
            get {
                return ResourceManager.GetString("ACTIONSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Cause..
        /// </summary>
        internal static string CAUSE_MISSING {
            get {
                return ResourceManager.GetString("CAUSE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Completion date for this Work Order..
        /// </summary>
        internal static string COMPLETIONDATE_MISSING {
            get {
                return ResourceManager.GetString("COMPLETIONDATE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer..
        /// </summary>
        internal static string CUSTOMER_MISSING {
            get {
                return ResourceManager.GetString("CUSTOMER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Customer found for selected Shop , please add Customer to Shop from Master Data Add Customer module..
        /// </summary>
        internal static string CUSTOMER_UNAVAILABLE {
            get {
                return ResourceManager.GetString("CUSTOMER_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert valid Equipment Number..
        /// </summary>
        internal static string EQP_MISSING {
            get {
                return ResourceManager.GetString("EQP_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert unique Equipment Number..
        /// </summary>
        internal static string EQP_NOTUNIQUE {
            get {
                return ResourceManager.GetString("EQP_NOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide value for Import tax cost for this Work Order..
        /// </summary>
        internal static string IMPORTTAXCOST_MISSING {
            get {
                return ResourceManager.GetString("IMPORTTAXCOST_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect input provided. Please verify..
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Mode..
        /// </summary>
        internal static string MODE_MISSING {
            get {
                return ResourceManager.GetString("MODE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform %% due to some error, please try in a while..
        /// </summary>
        internal static string NETWORK_PROBLEM {
            get {
                return ResourceManager.GetString("NETWORK_PROBLEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select unique Owner Supplied Parts Number for Spare part..
        /// </summary>
        internal static string OWNERSPNSP_NOTUNIQUE {
            get {
                return ResourceManager.GetString("OWNERSPNSP_NOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter remarks for this Work Order..
        /// </summary>
        internal static string REMARKS_MISSING {
            get {
                return ResourceManager.GetString("REMARKS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields for each Repair(s) entry..
        /// </summary>
        internal static string REPAIRPART_COMPLETEHIGHLIGHTEDENTRY {
            get {
                return ResourceManager.GetString("REPAIRPART_COMPLETEHIGHLIGHTEDENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pieces allowed for selected Repair Code is.
        /// </summary>
        internal static string REPAIRPART_EXCEEDMAXQUANT {
            get {
                return ResourceManager.GetString("REPAIRPART_EXCEEDMAXQUANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Repair(s) entry must be completely filled for this WO..
        /// </summary>
        internal static string REPAIRPART_INCOMPLETEENTRY {
            get {
                return ResourceManager.GetString("REPAIRPART_INCOMPLETEENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair piece count is required for repair code..
        /// </summary>
        internal static string REPAIRPART_PIECEMISSING {
            get {
                return ResourceManager.GetString("REPAIRPART_PIECEMISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some Repair Code to fetch the hour(s) from Get Hours..
        /// </summary>
        internal static string REPCODERP_MISSING {
            get {
                return ResourceManager.GetString("REPCODERP_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select unique Repair Code for Repair part..
        /// </summary>
        internal static string REPCODERP_NOTUNIQUE {
            get {
                return ResourceManager.GetString("REPCODERP_NOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select unique Repair Code for Spare part..
        /// </summary>
        internal static string REPCODESP_NOTUNIQUE {
            get {
                return ResourceManager.GetString("REPCODESP_NOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container type not received from RKEM or RKEM call not performed..
        /// </summary>
        internal static string RKEM_NOTCALLED {
            get {
                return ResourceManager.GetString("RKEM_NOTCALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide value for Sales tax Labour cost for this Work Order..
        /// </summary>
        internal static string SALESTAXLC_MISSING {
            get {
                return ResourceManager.GetString("SALESTAXLC_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide value for Sales tax Part(s) cost for this Work Order..
        /// </summary>
        internal static string SALESTAXPC_MISSING {
            get {
                return ResourceManager.GetString("SALESTAXPC_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : .
        /// </summary>
        internal static string sERROR {
            get {
                return ResourceManager.GetString("sERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Shop..
        /// </summary>
        internal static string SHOP_MISSING {
            get {
                return ResourceManager.GetString("SHOP_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Shop ,Customer and Currency details. Please reload the page again..
        /// </summary>
        internal static string SHOP_UNAVAILABLE {
            get {
                return ResourceManager.GetString("SHOP_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info : .
        /// </summary>
        internal static string sINFO {
            get {
                return ResourceManager.GetString("sINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Repair Code in Spare part(s) list must have reference in Repair Code of Repair List..
        /// </summary>
        internal static string SPAREPART_EXTRAREPCODE {
            get {
                return ResourceManager.GetString("SPAREPART_EXTRAREPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success : .
        /// </summary>
        internal static string sSUCCESS {
            get {
                return ResourceManager.GetString("sSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : .
        /// </summary>
        internal static string sWARNING {
            get {
                return ResourceManager.GetString("sWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Third Party Port number..
        /// </summary>
        internal static string THIRDPARTY_MISSING {
            get {
                return ResourceManager.GetString("THIRDPARTY_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert valid Vendor Reference Number..
        /// </summary>
        internal static string VENDOR_MISSING {
            get {
                return ResourceManager.GetString("VENDOR_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert unique Vendor Reference Number..
        /// </summary>
        internal static string VENDOR_NOTUNIQUE {
            get {
                return ResourceManager.GetString("VENDOR_NOTUNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Work Order details.Please wait....
        /// </summary>
        internal static string WAITINFO {
            get {
                return ResourceManager.GetString("WAITINFO", resourceCulture);
            }
        }
    }
}
